#pragma once
// Generated by tools/build_animations.py — do not edit by hand.
// Source: tools/animations.json. Regenerate after manifest changes.

// Celebration animations
#include "animations/panda.h"
#include "animations/panda2.h"
#include "animations/marcel.h"
#include "animations/david.h"
#include "animations/richard.h"
#include "animations/taylor.h"

// Idle background
#include "animations/clock_bg.h"

// drawGifFrame must be defined in the including translation unit *before* this header is included.

static void drawPanda(uint32_t elapsed) {
  static int16_t lastIdx = -1;
  drawGifFrame(elapsed, &pandaFrames[0][0], pandaDelaysMs,
               PANDA_FRAMES, PANDA_TOTAL_MS, PANDA_W, PANDA_H, lastIdx);
}

static void drawPanda2(uint32_t elapsed) {
  static int16_t lastIdx = -1;
  drawGifFrame(elapsed, &panda2Frames[0][0], panda2DelaysMs,
               PANDA2_FRAMES, PANDA2_TOTAL_MS, PANDA2_W, PANDA2_H, lastIdx);
}

static void drawMarcel(uint32_t elapsed) {
  static int16_t lastIdx = -1;
  drawGifFrame(elapsed, &marcelFrames[0][0], marcelDelaysMs,
               MARCEL_FRAMES, MARCEL_TOTAL_MS, MARCEL_W, MARCEL_H, lastIdx);
}

static void drawDavid(uint32_t elapsed) {
  static int16_t lastIdx = -1;
  drawGifFrame(elapsed, &davidFrames[0][0], davidDelaysMs,
               DAVID_FRAMES, DAVID_TOTAL_MS, DAVID_W, DAVID_H, lastIdx);
}

static void drawRichard(uint32_t elapsed) {
  static int16_t lastIdx = -1;
  drawGifFrame(elapsed, &richardFrames[0][0], richardDelaysMs,
               RICHARD_FRAMES, RICHARD_TOTAL_MS, RICHARD_W, RICHARD_H, lastIdx);
}

static void drawTaylor(uint32_t elapsed) {
  static int16_t lastIdx = -1;
  drawGifFrame(elapsed, &taylorFrames[0][0], taylorDelaysMs,
               TAYLOR_FRAMES, TAYLOR_TOTAL_MS, TAYLOR_W, TAYLOR_H, lastIdx);
}

// Use this macro inside ANIMATIONS[] in main.cpp.
#define ASSET_ANIMATION_ENTRIES \
  { "panda", drawPanda, true }, \
  { "panda2", drawPanda2, true }, \
  { "marcel", drawMarcel, true }, \
  { "david", drawDavid, true }, \
  { "richard", drawRichard, true }, \
  { "taylor", drawTaylor, true },
