#!/usr/bin/env python3
"""Convert every source listed in tools/animations.json to its include/animations/<name>.h header.

Sources can be animated GIFs **or static PNGs** (single-frame) — both flow
through gif_to_rgb565.py via PIL, so a .png becomes a 1-frame "animation".

Reads the manifest, runs gif_to_rgb565.py for each entry with the listed args,
and writes the output to include/animations/<name>.h.

Usage:
  cd led-panel-firmware
  python3 tools/build_animations.py

Exits non-zero on any conversion failure so CI can fail loudly.
"""

import argparse
import json
import subprocess
import sys
from pathlib import Path


def main() -> int:
    p = argparse.ArgumentParser()
    p.add_argument(
        "--list",
        action="store_true",
        help="print the asset inventory and exit (no conversion)",
    )
    cli = p.parse_args()

    here = Path(__file__).resolve().parent
    manifest_path = here / "animations.json"
    gifs_dir = here / "gifs"
    out_dir = here.parent / "include" / "animations"
    converter = here / "gif_to_rgb565.py"

    if not manifest_path.exists():
        print(f"error: manifest not found at {manifest_path}", file=sys.stderr)
        return 1

    entries = json.loads(manifest_path.read_text())

    if cli.list:
        print(f"{'kind':<12} {'name':<10} {'source':<14} {'status'}")
        print("-" * 60)
        for entry in entries:
            kind = entry.get("kind", "?")
            name = entry["name"]
            src = entry["source"]
            present = (gifs_dir / src).exists()
            optional = entry.get("optional", False)
            status = "present" if present else ("optional/missing" if optional else "MISSING")
            print(f"{kind:<12} {name:<10} {src:<14} {status}")
        return 0

    out_dir.mkdir(parents=True, exist_ok=True)

    failed: list[str] = []
    built = 0
    for entry in entries:
        source = gifs_dir / entry["source"]
        name = entry["name"]
        args = entry.get("args", [])
        optional = entry.get("optional", False)
        out_path = out_dir / f"{name}.h"

        if not source.exists():
            if optional:
                print(f"skip {name}: optional, source {source.name} not present")
                continue
            print(f"skip {name}: source {source} missing", file=sys.stderr)
            failed.append(name)
            continue

        cmd = ["python3", str(converter), str(source), "--name", name, *args]
        print(f"build {name}: {' '.join(cmd)}")
        try:
            with out_path.open("w") as f:
                subprocess.run(cmd, stdout=f, check=True)
            built += 1
        except subprocess.CalledProcessError as e:
            print(f"error: conversion failed for {name}: {e}", file=sys.stderr)
            failed.append(name)

    if failed:
        print(f"failed: {', '.join(failed)}", file=sys.stderr)
        return 1

    write_registry(entries, out_dir / "_registry.h")
    print(f"built {built} animation headers, regenerated _registry.h")
    return 0


def write_registry(entries: list[dict], path: Path) -> None:
    """Generate _registry.h: #includes + wrappers + ASSET_ANIMATION_ENTRIES macro.

    main.cpp #includes this once (after drawGifFrame is defined) and the
    macro is used inline in ANIMATIONS[]. Adding/removing an animation is now
    a manifest-only change; main.cpp doesn't move.
    """
    celebrations = [e for e in entries if e.get("kind", "celebration") == "celebration"]
    idle_bgs = [e for e in entries if e.get("kind") == "idle_bg"]

    lines: list[str] = []
    lines.append("#pragma once")
    lines.append("// Generated by tools/build_animations.py — do not edit by hand.")
    lines.append("// Source: tools/animations.json. Regenerate after manifest changes.")
    lines.append("")
    lines.append("// Celebration animations")
    for e in celebrations:
        lines.append(f'#include "animations/{e["name"]}.h"')
    if idle_bgs:
        lines.append("")
        lines.append("// Idle background")
        for e in idle_bgs:
            lines.append(f'#include "animations/{e["name"]}.h"')
    lines.append("")
    lines.append(
        "// drawGifFrame must be defined in the including translation unit "
        "*before* this header is included."
    )
    lines.append("")
    for e in celebrations:
        name = e["name"]
        wrap = "draw" + name[0].upper() + name[1:]
        upper = name.upper()
        var = name + "Frames"
        delays = name + "DelaysMs"
        lines.append(f"static void {wrap}(uint32_t elapsed) {{")
        lines.append(f"  static int16_t lastIdx = -1;")
        lines.append(
            f"  drawGifFrame(elapsed, &{var}[0][0], {delays},"
        )
        lines.append(
            f"               {upper}_FRAMES, {upper}_TOTAL_MS, {upper}_W, {upper}_H, lastIdx);"
        )
        lines.append("}")
        lines.append("")
    lines.append("// Use this macro inside ANIMATIONS[] in main.cpp.")
    lines.append("#define ASSET_ANIMATION_ENTRIES \\")
    for i, e in enumerate(celebrations):
        name = e["name"]
        wrap = "draw" + name[0].upper() + name[1:]
        suffix = " \\" if i < len(celebrations) - 1 else ""
        lines.append(f'  {{ "{name}", {wrap}, true }},{suffix}')
    lines.append("")

    path.write_text("\n".join(lines))


if __name__ == "__main__":
    sys.exit(main())
